
CREATE TABLE Document (
  ID BIGINT NOT NULL,
  GROUP_ID VARCHAR(120) NOT NULL,
  ARTIFACT_ID VARCHAR (200)  NOT NULL ,
  VERSION VARCHAR (200)  NOT NULL
);

INSERT INTO Document(ID, GROUP_ID, ARTIFACT_ID, VERSION) VALUES (1, 'a', 'b', 'c');
INSERT INTO Document(ID, GROUP_ID, ARTIFACT_ID, VERSION) VALUES (2, 'd', 'e', 'f');

COMMIT;
