package io.ushi.springboot.model;

public class Document {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Document.ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Document.GROUP_ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Document.ARTIFACT_ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    private String artifactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Document.VERSION
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Document.ID
     *
     * @return the value of Document.ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Document.ID
     *
     * @param id the value for Document.ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Document.GROUP_ID
     *
     * @return the value of Document.GROUP_ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Document.GROUP_ID
     *
     * @param groupId the value for Document.GROUP_ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Document.ARTIFACT_ID
     *
     * @return the value of Document.ARTIFACT_ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public String getArtifactId() {
        return artifactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Document.ARTIFACT_ID
     *
     * @param artifactId the value for Document.ARTIFACT_ID
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public void setArtifactId(String artifactId) {
        this.artifactId = artifactId == null ? null : artifactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Document.VERSION
     *
     * @return the value of Document.VERSION
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Document.VERSION
     *
     * @param version the value for Document.VERSION
     *
     * @mbg.generated Thu Sep 14 21:18:18 CST 2017
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}